### ISSUE TITLE
A few sample WAV files unavailable (404 error)

### ISSUE THREAD

**Issue by scottveirs** [coastal-science/call-catalog-viewer#32]
In viewing the draft catalogue for SRKW calls today (and in recent weeks), I've found a small selection of the audio samples displaying an "Access Unavailable" graphic. Upon inspection when I select the play button under one of these graphics, there is a 404 error (see screenshot).

Maybe a file name changed, or a sample was removed from the catalogue's media directory?

<img width="1787" alt="Screenshot 2023-09-14 at 10 19 03 AM" src="https://github.com/coastal-science/call-catalog-viewer/assets/14044595/d83a7876-5ebb-4134-b794-353fe9fe07f7">

**Comment by VWJF** [comment]
Hi @scottveirs 
 
This issue is a consequence that @JKBF has curated (add/removed/grouped) specific calls in his in-development version of the catalogue, and the main version (what you see) is out of sync until we can designate @JKBF's version as the principal catalogue.

> it was a revision to correct the call type S13, which should not have been split into subtypes.
> -- @JKBF

 
I have reverted the catalogue you see to the previous version (without the missing entries) until we get @JKBF’s consent to replace it with his version.
 
Apologies for the bug, and thanks for your patience.
