### ISSUE TITLE
Typos in licence (sic) and FAQ pages

### ISSUE THREAD

**Issue by scottveirs** [coastal-science/call-catalog-viewer#34]
The word license is misspelled as `licence` in many places, at least these two pages:

1. [https://orca.research.sfu.ca/johnf/faq.html#how-to-use-this-site](https://orca.research.sfu.ca/johnf/faq.html#how-to-use-this-site)
2. [https://orca.research.sfu.ca/catalogue/license.html](https://orca.research.sfu.ca/catalogue/license.html)

Both the title of the `LICENCE` page and the menu item it are misspelled.

Also, on the `license.html` page, in its last sentence, the word referring is misspelled as `refering` -- 

<img width="843" alt="Screenshot 2023-10-27 at 12 20 59 AM" src="https://github.com/coastal-science/call-catalog-viewer/assets/14044595/f34dfa47-1227-463c-8da1-1b111f5051b6">

**Comment by VWJF** [comment]
This has been addressed and will be reflected in an upcoming PR #36

**Comment by scottveirs** [comment]
@VWJF It's still not addressed here -- https://orca.research.sfu.ca/call-library/license.html?v=20240530-1727

**Comment by VWJF** [comment]
@scottveirs, I should have documented it here.

It's [not actually a misspelling](https://www.grammarly.com/blog/licence-license/#:~:text=In%20American%20English%2C%20the%20noun,or%20allowed%20to%20do%20something.). 

The executive decision was made (@JKBF and @rutherfordjoy) to revert to _licence_ (noun) spelling to _reflect the Canadian origin and heritage_ of the catalogue [JKBF]. That's also why it is referred to as _catalogue_ instead of _catalog_ in as many places as we can without making drastic changes. 

I hope this addresses the uneasiness when you see the alternate spellings. 
🙂🇨🇦

**Comment by scottveirs** [comment]
Ok, great! Thank you for clarifying. I had no idea the Canadian spelling
differs!
